export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCESS = 'FETCH_TOKEN_SUCESS';
export const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
export const SET_LOGGED_IN_LOGGED_OUT = 'SET_LOGGED_IN_LOGGED_OUT';
export const SET_USER_AGENT = 'SET_USER_AGENT';
export const SET_REFRESHED_TOKEN = 'SET_REFRESHED_TOKEN';
export const FETCH_REFRESHED_TOKEN_ERROR = 'FETCH_REFRESHED_TOKEN_ERROR';
export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const RESET_BOOKING_DATA = 'RESET_BOOKING_DATA';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';

export const SET_LOGIN_STATE = 'LOGIN_STATE';
